joy:
  ros__parameters:
    #device_name: /dev/input/joypad-f710
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 30.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 4
          scale: 1.5
          offset: 0.0
        drive-steering_angle:
          axis: 0
          scale: -0.28
          offset: 0.0

    autonomous_control:
      type: topic
      interface_type: std_msgs/msg/Bool
      topic_name: pause_navigation
      deadman_buttons: [5]
      message_value:
        data:
          value: False
