ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : ack_vel
        timeout : 0.1
        priority: 10
      joystick:
        topic   : teleop
        timeout : 0.1
        priority: 100